namespace CameraCaptureApp.Forms
{
    partial class MeterWheelExtensionCompareForm
    {
        private System.ComponentModel.IContainer components = null;
        private System.Windows.Forms.Label labelChannelHeader;
        private System.Windows.Forms.Label labelMaskHeader;
        private System.Windows.Forms.Label labelOffsetHeader;
        private System.Windows.Forms.Label labelPulseWidthHeader;
        private System.Windows.Forms.Label labelOutputHeader;
        private System.Windows.Forms.Label labelStatusHeader;
        private System.Windows.Forms.Label labelCmp0;
        private System.Windows.Forms.Label labelCmp1;
        private System.Windows.Forms.Label labelCmp2;
        private System.Windows.Forms.Label labelCmp3;
        private System.Windows.Forms.Label labelCmp4;
        private System.Windows.Forms.Label labelCmp5;
        private System.Windows.Forms.Label labelCmp6;
        private System.Windows.Forms.Label labelCmp7;
        private System.Windows.Forms.CheckBox checkMask0;
        private System.Windows.Forms.CheckBox checkMask1;
        private System.Windows.Forms.CheckBox checkMask2;
        private System.Windows.Forms.CheckBox checkMask3;
        private System.Windows.Forms.CheckBox checkMask4;
        private System.Windows.Forms.CheckBox checkMask5;
        private System.Windows.Forms.CheckBox checkMask6;
        private System.Windows.Forms.CheckBox checkMask7;
        private System.Windows.Forms.NumericUpDown numericOffset0;
        private System.Windows.Forms.NumericUpDown numericOffset1;
        private System.Windows.Forms.NumericUpDown numericOffset2;
        private System.Windows.Forms.NumericUpDown numericOffset3;
        private System.Windows.Forms.NumericUpDown numericOffset4;
        private System.Windows.Forms.NumericUpDown numericOffset5;
        private System.Windows.Forms.NumericUpDown numericOffset6;
        private System.Windows.Forms.NumericUpDown numericOffset7;
        private System.Windows.Forms.NumericUpDown numericPulseWidth0;
        private System.Windows.Forms.NumericUpDown numericPulseWidth1;
        private System.Windows.Forms.NumericUpDown numericPulseWidth2;
        private System.Windows.Forms.NumericUpDown numericPulseWidth3;
        private System.Windows.Forms.NumericUpDown numericPulseWidth4;
        private System.Windows.Forms.NumericUpDown numericPulseWidth5;
        private System.Windows.Forms.NumericUpDown numericPulseWidth6;
        private System.Windows.Forms.NumericUpDown numericPulseWidth7;
        private System.Windows.Forms.CheckBox checkOutput0;
        private System.Windows.Forms.CheckBox checkOutput1;
        private System.Windows.Forms.CheckBox checkOutput2;
        private System.Windows.Forms.CheckBox checkOutput3;
        private System.Windows.Forms.CheckBox checkOutput4;
        private System.Windows.Forms.CheckBox checkOutput5;
        private System.Windows.Forms.CheckBox checkOutput6;
        private System.Windows.Forms.CheckBox checkOutput7;
        private System.Windows.Forms.CheckBox checkStatus0;
        private System.Windows.Forms.CheckBox checkStatus1;
        private System.Windows.Forms.CheckBox checkStatus2;
        private System.Windows.Forms.CheckBox checkStatus3;
        private System.Windows.Forms.CheckBox checkStatus4;
        private System.Windows.Forms.CheckBox checkStatus5;
        private System.Windows.Forms.CheckBox checkStatus6;
        private System.Windows.Forms.CheckBox checkStatus7;
        private System.Windows.Forms.Button buttonOk;
        private System.Windows.Forms.Button buttonCancel;
        private System.Windows.Forms.Button buttonApply;
        private System.Windows.Forms.Label labelStatus;
        private System.Windows.Forms.Timer timerRefresh;

        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }

            base.Dispose(disposing);
        }

        private void InitializeComponent()
        {
            this.components = new System.ComponentModel.Container();
            this.labelChannelHeader = new System.Windows.Forms.Label();
            this.labelMaskHeader = new System.Windows.Forms.Label();
            this.labelOffsetHeader = new System.Windows.Forms.Label();
            this.labelPulseWidthHeader = new System.Windows.Forms.Label();
            this.labelOutputHeader = new System.Windows.Forms.Label();
            this.labelStatusHeader = new System.Windows.Forms.Label();
            this.labelCmp0 = new System.Windows.Forms.Label();
            this.labelCmp1 = new System.Windows.Forms.Label();
            this.labelCmp2 = new System.Windows.Forms.Label();
            this.labelCmp3 = new System.Windows.Forms.Label();
            this.labelCmp4 = new System.Windows.Forms.Label();
            this.labelCmp5 = new System.Windows.Forms.Label();
            this.labelCmp6 = new System.Windows.Forms.Label();
            this.labelCmp7 = new System.Windows.Forms.Label();
            this.checkMask0 = new System.Windows.Forms.CheckBox();
            this.checkMask1 = new System.Windows.Forms.CheckBox();
            this.checkMask2 = new System.Windows.Forms.CheckBox();
            this.checkMask3 = new System.Windows.Forms.CheckBox();
            this.checkMask4 = new System.Windows.Forms.CheckBox();
            this.checkMask5 = new System.Windows.Forms.CheckBox();
            this.checkMask6 = new System.Windows.Forms.CheckBox();
            this.checkMask7 = new System.Windows.Forms.CheckBox();
            this.numericOffset0 = new System.Windows.Forms.NumericUpDown();
            this.numericOffset1 = new System.Windows.Forms.NumericUpDown();
            this.numericOffset2 = new System.Windows.Forms.NumericUpDown();
            this.numericOffset3 = new System.Windows.Forms.NumericUpDown();
            this.numericOffset4 = new System.Windows.Forms.NumericUpDown();
            this.numericOffset5 = new System.Windows.Forms.NumericUpDown();
            this.numericOffset6 = new System.Windows.Forms.NumericUpDown();
            this.numericOffset7 = new System.Windows.Forms.NumericUpDown();
            this.numericPulseWidth0 = new System.Windows.Forms.NumericUpDown();
            this.numericPulseWidth1 = new System.Windows.Forms.NumericUpDown();
            this.numericPulseWidth2 = new System.Windows.Forms.NumericUpDown();
            this.numericPulseWidth3 = new System.Windows.Forms.NumericUpDown();
            this.numericPulseWidth4 = new System.Windows.Forms.NumericUpDown();
            this.numericPulseWidth5 = new System.Windows.Forms.NumericUpDown();
            this.numericPulseWidth6 = new System.Windows.Forms.NumericUpDown();
            this.numericPulseWidth7 = new System.Windows.Forms.NumericUpDown();
            this.checkOutput0 = new System.Windows.Forms.CheckBox();
            this.checkOutput1 = new System.Windows.Forms.CheckBox();
            this.checkOutput2 = new System.Windows.Forms.CheckBox();
            this.checkOutput3 = new System.Windows.Forms.CheckBox();
            this.checkOutput4 = new System.Windows.Forms.CheckBox();
            this.checkOutput5 = new System.Windows.Forms.CheckBox();
            this.checkOutput6 = new System.Windows.Forms.CheckBox();
            this.checkOutput7 = new System.Windows.Forms.CheckBox();
            this.checkStatus0 = new System.Windows.Forms.CheckBox();
            this.checkStatus1 = new System.Windows.Forms.CheckBox();
            this.checkStatus2 = new System.Windows.Forms.CheckBox();
            this.checkStatus3 = new System.Windows.Forms.CheckBox();
            this.checkStatus4 = new System.Windows.Forms.CheckBox();
            this.checkStatus5 = new System.Windows.Forms.CheckBox();
            this.checkStatus6 = new System.Windows.Forms.CheckBox();
            this.checkStatus7 = new System.Windows.Forms.CheckBox();
            this.buttonOk = new System.Windows.Forms.Button();
            this.buttonCancel = new System.Windows.Forms.Button();
            this.buttonApply = new System.Windows.Forms.Button();
            this.labelStatus = new System.Windows.Forms.Label();
            this.timerRefresh = new System.Windows.Forms.Timer(this.components);
            ((System.ComponentModel.ISupportInitialize)(this.numericOffset0)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.numericOffset1)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.numericOffset2)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.numericOffset3)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.numericOffset4)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.numericOffset5)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.numericOffset6)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.numericOffset7)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.numericPulseWidth0)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.numericPulseWidth1)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.numericPulseWidth2)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.numericPulseWidth3)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.numericPulseWidth4)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.numericPulseWidth5)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.numericPulseWidth6)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.numericPulseWidth7)).BeginInit();
            this.SuspendLayout();
            this.labelChannelHeader.AutoSize = false;
            this.labelChannelHeader.Font = new System.Drawing.Font("Microsoft JhengHei UI", 9F, System.Drawing.FontStyle.Bold);
            this.labelChannelHeader.Location = new System.Drawing.Point(18, 18);
            this.labelChannelHeader.Size = new System.Drawing.Size(80, 22);
            this.labelChannelHeader.Text = "Channel";
            this.labelMaskHeader.AutoSize = false;
            this.labelMaskHeader.Font = new System.Drawing.Font("Microsoft JhengHei UI", 9F, System.Drawing.FontStyle.Bold);
            this.labelMaskHeader.Location = new System.Drawing.Point(112, 18);
            this.labelMaskHeader.Size = new System.Drawing.Size(60, 22);
            this.labelMaskHeader.Text = "Mask";
            this.labelOffsetHeader.AutoSize = false;
            this.labelOffsetHeader.Font = new System.Drawing.Font("Microsoft JhengHei UI", 9F, System.Drawing.FontStyle.Bold);
            this.labelOffsetHeader.Location = new System.Drawing.Point(196, 18);
            this.labelOffsetHeader.Size = new System.Drawing.Size(120, 22);
            this.labelOffsetHeader.Text = "Offset Compare";
            this.labelPulseWidthHeader.AutoSize = false;
            this.labelPulseWidthHeader.Font = new System.Drawing.Font("Microsoft JhengHei UI", 9F, System.Drawing.FontStyle.Bold);
            this.labelPulseWidthHeader.Location = new System.Drawing.Point(338, 18);
            this.labelPulseWidthHeader.Size = new System.Drawing.Size(100, 22);
            this.labelPulseWidthHeader.Text = "Pulse Width";
            this.labelOutputHeader.AutoSize = false;
            this.labelOutputHeader.Font = new System.Drawing.Font("Microsoft JhengHei UI", 9F, System.Drawing.FontStyle.Bold);
            this.labelOutputHeader.Location = new System.Drawing.Point(466, 18);
            this.labelOutputHeader.Size = new System.Drawing.Size(72, 22);
            this.labelOutputHeader.Text = "Output";
            this.labelStatusHeader.AutoSize = false;
            this.labelStatusHeader.Font = new System.Drawing.Font("Microsoft JhengHei UI", 9F, System.Drawing.FontStyle.Bold);
            this.labelStatusHeader.Location = new System.Drawing.Point(558, 18);
            this.labelStatusHeader.Size = new System.Drawing.Size(70, 22);
            this.labelStatusHeader.Text = "Status";
            this.labelCmp0.Location = new System.Drawing.Point(18, 52);
            this.labelCmp0.Size = new System.Drawing.Size(80, 20);
            this.labelCmp0.Text = "CMP0";
            this.labelCmp1.Location = new System.Drawing.Point(18, 82);
            this.labelCmp1.Size = new System.Drawing.Size(80, 20);
            this.labelCmp1.Text = "CMP1";
            this.labelCmp2.Location = new System.Drawing.Point(18, 112);
            this.labelCmp2.Size = new System.Drawing.Size(80, 20);
            this.labelCmp2.Text = "CMP2";
            this.labelCmp3.Location = new System.Drawing.Point(18, 142);
            this.labelCmp3.Size = new System.Drawing.Size(80, 20);
            this.labelCmp3.Text = "CMP3";
            this.labelCmp4.Location = new System.Drawing.Point(18, 172);
            this.labelCmp4.Size = new System.Drawing.Size(80, 20);
            this.labelCmp4.Text = "CMP4";
            this.labelCmp5.Location = new System.Drawing.Point(18, 202);
            this.labelCmp5.Size = new System.Drawing.Size(80, 20);
            this.labelCmp5.Text = "CMP5";
            this.labelCmp6.Location = new System.Drawing.Point(18, 232);
            this.labelCmp6.Size = new System.Drawing.Size(80, 20);
            this.labelCmp6.Text = "CMP6";
            this.labelCmp7.Location = new System.Drawing.Point(18, 262);
            this.labelCmp7.Size = new System.Drawing.Size(80, 20);
            this.labelCmp7.Text = "CMP7";
            this.checkMask0.Location = new System.Drawing.Point(124, 52);
            this.checkMask1.Location = new System.Drawing.Point(124, 82);
            this.checkMask2.Location = new System.Drawing.Point(124, 112);
            this.checkMask3.Location = new System.Drawing.Point(124, 142);
            this.checkMask4.Location = new System.Drawing.Point(124, 172);
            this.checkMask5.Location = new System.Drawing.Point(124, 202);
            this.checkMask6.Location = new System.Drawing.Point(124, 232);
            this.checkMask7.Location = new System.Drawing.Point(124, 262);
            this.checkMask0.Size = new System.Drawing.Size(22, 22);
            this.checkMask1.Size = new System.Drawing.Size(22, 22);
            this.checkMask2.Size = new System.Drawing.Size(22, 22);
            this.checkMask3.Size = new System.Drawing.Size(22, 22);
            this.checkMask4.Size = new System.Drawing.Size(22, 22);
            this.checkMask5.Size = new System.Drawing.Size(22, 22);
            this.checkMask6.Size = new System.Drawing.Size(22, 22);
            this.checkMask7.Size = new System.Drawing.Size(22, 22);
            this.checkMask0.CheckedChanged += new System.EventHandler(this.checkMask_CheckedChanged);
            this.checkMask1.CheckedChanged += new System.EventHandler(this.checkMask_CheckedChanged);
            this.checkMask2.CheckedChanged += new System.EventHandler(this.checkMask_CheckedChanged);
            this.checkMask3.CheckedChanged += new System.EventHandler(this.checkMask_CheckedChanged);
            this.checkMask4.CheckedChanged += new System.EventHandler(this.checkMask_CheckedChanged);
            this.checkMask5.CheckedChanged += new System.EventHandler(this.checkMask_CheckedChanged);
            this.checkMask6.CheckedChanged += new System.EventHandler(this.checkMask_CheckedChanged);
            this.checkMask7.CheckedChanged += new System.EventHandler(this.checkMask_CheckedChanged);
            this.numericOffset0.Location = new System.Drawing.Point(196, 48);
            this.numericOffset1.Location = new System.Drawing.Point(196, 78);
            this.numericOffset2.Location = new System.Drawing.Point(196, 108);
            this.numericOffset3.Location = new System.Drawing.Point(196, 138);
            this.numericOffset4.Location = new System.Drawing.Point(196, 168);
            this.numericOffset5.Location = new System.Drawing.Point(196, 198);
            this.numericOffset6.Location = new System.Drawing.Point(196, 228);
            this.numericOffset7.Location = new System.Drawing.Point(196, 258);
            this.numericOffset0.Minimum = -32768;
            this.numericOffset1.Minimum = -32768;
            this.numericOffset2.Minimum = -32768;
            this.numericOffset3.Minimum = -32768;
            this.numericOffset4.Minimum = -32768;
            this.numericOffset5.Minimum = -32768;
            this.numericOffset6.Minimum = -32768;
            this.numericOffset7.Minimum = -32768;
            this.numericOffset0.Maximum = 32767;
            this.numericOffset1.Maximum = 32767;
            this.numericOffset2.Maximum = 32767;
            this.numericOffset3.Maximum = 32767;
            this.numericOffset4.Maximum = 32767;
            this.numericOffset5.Maximum = 32767;
            this.numericOffset6.Maximum = 32767;
            this.numericOffset7.Maximum = 32767;
            this.numericOffset0.Size = new System.Drawing.Size(108, 25);
            this.numericOffset1.Size = new System.Drawing.Size(108, 25);
            this.numericOffset2.Size = new System.Drawing.Size(108, 25);
            this.numericOffset3.Size = new System.Drawing.Size(108, 25);
            this.numericOffset4.Size = new System.Drawing.Size(108, 25);
            this.numericOffset5.Size = new System.Drawing.Size(108, 25);
            this.numericOffset6.Size = new System.Drawing.Size(108, 25);
            this.numericOffset7.Size = new System.Drawing.Size(108, 25);
            this.numericPulseWidth0.Location = new System.Drawing.Point(338, 48);
            this.numericPulseWidth1.Location = new System.Drawing.Point(338, 78);
            this.numericPulseWidth2.Location = new System.Drawing.Point(338, 108);
            this.numericPulseWidth3.Location = new System.Drawing.Point(338, 138);
            this.numericPulseWidth4.Location = new System.Drawing.Point(338, 168);
            this.numericPulseWidth5.Location = new System.Drawing.Point(338, 198);
            this.numericPulseWidth6.Location = new System.Drawing.Point(338, 228);
            this.numericPulseWidth7.Location = new System.Drawing.Point(338, 258);
            this.numericPulseWidth0.Maximum = 65535;
            this.numericPulseWidth1.Maximum = 65535;
            this.numericPulseWidth2.Maximum = 65535;
            this.numericPulseWidth3.Maximum = 65535;
            this.numericPulseWidth4.Maximum = 65535;
            this.numericPulseWidth5.Maximum = 65535;
            this.numericPulseWidth6.Maximum = 65535;
            this.numericPulseWidth7.Maximum = 65535;
            this.numericPulseWidth0.Size = new System.Drawing.Size(108, 25);
            this.numericPulseWidth1.Size = new System.Drawing.Size(108, 25);
            this.numericPulseWidth2.Size = new System.Drawing.Size(108, 25);
            this.numericPulseWidth3.Size = new System.Drawing.Size(108, 25);
            this.numericPulseWidth4.Size = new System.Drawing.Size(108, 25);
            this.numericPulseWidth5.Size = new System.Drawing.Size(108, 25);
            this.numericPulseWidth6.Size = new System.Drawing.Size(108, 25);
            this.numericPulseWidth7.Size = new System.Drawing.Size(108, 25);
            this.checkOutput0.Location = new System.Drawing.Point(486, 52);
            this.checkOutput1.Location = new System.Drawing.Point(486, 82);
            this.checkOutput2.Location = new System.Drawing.Point(486, 112);
            this.checkOutput3.Location = new System.Drawing.Point(486, 142);
            this.checkOutput4.Location = new System.Drawing.Point(486, 172);
            this.checkOutput5.Location = new System.Drawing.Point(486, 202);
            this.checkOutput6.Location = new System.Drawing.Point(486, 232);
            this.checkOutput7.Location = new System.Drawing.Point(486, 262);
            this.checkStatus0.Location = new System.Drawing.Point(578, 52);
            this.checkStatus1.Location = new System.Drawing.Point(578, 82);
            this.checkStatus2.Location = new System.Drawing.Point(578, 112);
            this.checkStatus3.Location = new System.Drawing.Point(578, 142);
            this.checkStatus4.Location = new System.Drawing.Point(578, 172);
            this.checkStatus5.Location = new System.Drawing.Point(578, 202);
            this.checkStatus6.Location = new System.Drawing.Point(578, 232);
            this.checkStatus7.Location = new System.Drawing.Point(578, 262);
            this.checkOutput0.Size = new System.Drawing.Size(22, 22);
            this.checkOutput1.Size = new System.Drawing.Size(22, 22);
            this.checkOutput2.Size = new System.Drawing.Size(22, 22);
            this.checkOutput3.Size = new System.Drawing.Size(22, 22);
            this.checkOutput4.Size = new System.Drawing.Size(22, 22);
            this.checkOutput5.Size = new System.Drawing.Size(22, 22);
            this.checkOutput6.Size = new System.Drawing.Size(22, 22);
            this.checkOutput7.Size = new System.Drawing.Size(22, 22);
            this.checkStatus0.Size = new System.Drawing.Size(22, 22);
            this.checkStatus1.Size = new System.Drawing.Size(22, 22);
            this.checkStatus2.Size = new System.Drawing.Size(22, 22);
            this.checkStatus3.Size = new System.Drawing.Size(22, 22);
            this.checkStatus4.Size = new System.Drawing.Size(22, 22);
            this.checkStatus5.Size = new System.Drawing.Size(22, 22);
            this.checkStatus6.Size = new System.Drawing.Size(22, 22);
            this.checkStatus7.Size = new System.Drawing.Size(22, 22);
            this.checkStatus0.Enabled = false;
            this.checkStatus1.Enabled = false;
            this.checkStatus2.Enabled = false;
            this.checkStatus3.Enabled = false;
            this.checkStatus4.Enabled = false;
            this.checkStatus5.Enabled = false;
            this.checkStatus6.Enabled = false;
            this.checkStatus7.Enabled = false;
            this.buttonOk.BackColor = System.Drawing.Color.FromArgb(84, 120, 196);
            this.buttonOk.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.buttonOk.ForeColor = System.Drawing.Color.White;
            this.buttonOk.Location = new System.Drawing.Point(318, 306);
            this.buttonOk.Size = new System.Drawing.Size(72, 30);
            this.buttonOk.Text = "OK";
            this.buttonCancel.BackColor = System.Drawing.Color.FromArgb(84, 120, 196);
            this.buttonCancel.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.buttonCancel.ForeColor = System.Drawing.Color.White;
            this.buttonCancel.Location = new System.Drawing.Point(400, 306);
            this.buttonCancel.Size = new System.Drawing.Size(82, 30);
            this.buttonCancel.Text = "Cancel";
            this.buttonApply.BackColor = System.Drawing.Color.FromArgb(84, 120, 196);
            this.buttonApply.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.buttonApply.ForeColor = System.Drawing.Color.White;
            this.buttonApply.Location = new System.Drawing.Point(494, 306);
            this.buttonApply.Size = new System.Drawing.Size(82, 30);
            this.buttonApply.Text = "Apply";
            this.buttonOk.Click += new System.EventHandler(this.buttonOk_Click);
            this.buttonCancel.Click += new System.EventHandler(this.buttonCancel_Click);
            this.buttonApply.Click += new System.EventHandler(this.buttonApply_Click);
            this.labelStatus.AutoSize = false;
            this.labelStatus.Location = new System.Drawing.Point(18, 310);
            this.labelStatus.Size = new System.Drawing.Size(280, 20);
            this.labelStatus.Text = "Ready";
            this.labelStatus.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.timerRefresh.Interval = 200;
            this.timerRefresh.Tick += new System.EventHandler(this.timerRefresh_Tick);
            this.AutoScaleDimensions = new System.Drawing.SizeF(8F, 17F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.BackColor = System.Drawing.Color.FromArgb(42, 48, 60);
            this.ClientSize = new System.Drawing.Size(640, 360);
            this.Controls.AddRange(new System.Windows.Forms.Control[] {
                this.labelChannelHeader, this.labelMaskHeader, this.labelOffsetHeader, this.labelPulseWidthHeader, this.labelOutputHeader, this.labelStatusHeader,
                this.labelCmp0, this.labelCmp1, this.labelCmp2, this.labelCmp3, this.labelCmp4, this.labelCmp5, this.labelCmp6, this.labelCmp7,
                this.checkMask0, this.checkMask1, this.checkMask2, this.checkMask3, this.checkMask4, this.checkMask5, this.checkMask6, this.checkMask7,
                this.numericOffset0, this.numericOffset1, this.numericOffset2, this.numericOffset3, this.numericOffset4, this.numericOffset5, this.numericOffset6, this.numericOffset7,
                this.numericPulseWidth0, this.numericPulseWidth1, this.numericPulseWidth2, this.numericPulseWidth3, this.numericPulseWidth4, this.numericPulseWidth5, this.numericPulseWidth6, this.numericPulseWidth7,
                this.checkOutput0, this.checkOutput1, this.checkOutput2, this.checkOutput3, this.checkOutput4, this.checkOutput5, this.checkOutput6, this.checkOutput7,
                this.checkStatus0, this.checkStatus1, this.checkStatus2, this.checkStatus3, this.checkStatus4, this.checkStatus5, this.checkStatus6, this.checkStatus7,
                this.buttonOk, this.buttonCancel, this.buttonApply, this.labelStatus});
            this.Font = new System.Drawing.Font("Microsoft JhengHei UI", 9F);
            this.ForeColor = System.Drawing.Color.White;
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.FixedDialog;
            this.MaximizeBox = false;
            this.MinimizeBox = false;
            this.Name = "MeterWheelExtensionCompareForm";
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterParent;
            this.Text = "Extension Compare";
            ((System.ComponentModel.ISupportInitialize)(this.numericOffset0)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.numericOffset1)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.numericOffset2)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.numericOffset3)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.numericOffset4)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.numericOffset5)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.numericOffset6)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.numericOffset7)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.numericPulseWidth0)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.numericPulseWidth1)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.numericPulseWidth2)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.numericPulseWidth3)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.numericPulseWidth4)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.numericPulseWidth5)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.numericPulseWidth6)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.numericPulseWidth7)).EndInit();
            this.ResumeLayout(false);
        }

    }
}
